### ISSUE TITLE
Regexp for cleaning blank lines is terribly slow

### ISSUE THREAD

**Issue by chrj** [eaigner/dkim#3]
Hello,

I've been testing your dkim package and with Go 1.3 i saw about 80% slowdown of signing speed. When I started profiling I found that most of the time was not spent signing or hashing. It was spent cleaning blank lines of the end of the message body.

In canonicalBody, instead of doing:

    rx3 := regexp.MustCompile(`[ \r\n]*\z`)
    body = rx3.ReplaceAll(body, []byte(""))

You could do this:

    body = bytes.TrimRight(body, " \r\n")

This gave me a significant speedup of about 8-9x and your tests still passes.

Do you see any problems with this implementation?

**Comment by eaigner** [comment]
It's not exactly equivalent because `[ \r\n]` trims all `SPACE`, `CR` and `LF` occurrences from the end. But what's definitely overkill is that I compile the `regexp` on every call instead of once outside the function scope.
